package keqing.pollution.api.utils;

import gregtech.api.util.Mods;
import net.minecraft.item.ItemStack;

public class ae2Index {
	public static ItemStack controller;
	public static ItemStack drive;
	public static ItemStack inscribe;
	public static ItemStack chest;
	public static ItemStack meInterface;
	public static ItemStack meFluidInterface;
	public static ItemStack mePatternInterface;
	public static ItemStack meCellWorkbench;
	public static ItemStack securityStation;
	public static ItemStack quartzGlass;
	public static ItemStack lightPanel;
	public static ItemStack mePanel;
	public static ItemStack mePatternTerminal;
	public static ItemStack mePatternTerminalEx;
	public static ItemStack mePortableCell;
	public static ItemStack meFluidTerminal;
	public static ItemStack inputBus;
	public static ItemStack fluidInputBus;
	public static ItemStack outputBus;
	public static ItemStack fluidOutputBus;
	public static ItemStack craftingUnit;
	public static ItemStack parallelProcessingUnit;
	public static ItemStack craftingStorage1k;
	public static ItemStack craftingStorage4k;
	public static ItemStack craftingStorage16k;
	public static ItemStack craftingStorage64k;
	public static ItemStack energyCell;
	public static ItemStack denseEnergyCell;
	public static ItemStack molecularAssembler;
	public static ItemStack logicModel;
	public static ItemStack logicBase;
	public static ItemStack logicProcessor;
	public static ItemStack calculationModel;
	public static ItemStack calculationBase;
	public static ItemStack calculationProcessor;
	public static ItemStack engineeringModel;
	public static ItemStack engineeringBase;
	public static ItemStack engineeringProcessor;
	public static ItemStack siliconModel;
	public static ItemStack skyCompass;
	public static ItemStack forming;
	public static ItemStack breaking;
	public static ItemStack siliconFiber;
	public static ItemStack meGlassCable;
	public static ItemStack meCable;
	public static ItemStack meCableDense;
	public static ItemStack meCableSmart;
	public static ItemStack basicCard;
	public static ItemStack advancedCard;
	public static ItemStack blankPattern;
	public static ItemStack meStorageCell;
	public static ItemStack cell1k;
	public static ItemStack storage1k;
	public static ItemStack cell4k;
	public static ItemStack storage4k;
	public static ItemStack cell16k;
	public static ItemStack storage16k;
	public static ItemStack cell64k;
	public static ItemStack storage64k;
	public static ItemStack fluidCell1k;
	public static ItemStack fluidStorage1k;
	public static ItemStack fluidCell4k;
	public static ItemStack fluidStorage4k;
	public static ItemStack fluidCell16k;
	public static ItemStack fluidStorage16k;
	public static ItemStack fluidCell64k;
	public static ItemStack fluidStorage64k;
	public static ItemStack p2p;
	public static ItemStack fluixpearl;
	public static ItemStack vibrantGlass;
	public static ItemStack energyAcceptor;


	public ae2Index() {
	}

	static {
		controller = Mods.AppliedEnergistics2.getItem("controller");
		drive = Mods.AppliedEnergistics2.getItem("drive");
		inscribe = Mods.AppliedEnergistics2.getItem("inscribe");
		chest = Mods.AppliedEnergistics2.getItem("chest");
		meInterface = Mods.AppliedEnergistics2.getItem("interface");
		meFluidInterface = Mods.AppliedEnergistics2.getItem("fluid_interface");
		mePatternInterface = Mods.AppliedEnergistics2.getItem("io_port");
		meCellWorkbench = Mods.AppliedEnergistics2.getItem("cell_workbench");
		securityStation = Mods.AppliedEnergistics2.getItem("security_station");
		quartzGlass = Mods.AppliedEnergistics2.getItem("quartz_glass");
		vibrantGlass = Mods.AppliedEnergistics2.getItem("quartz_vibrant_glass");
		lightPanel = Mods.AppliedEnergistics2.getItem("part", 180, 1);
		mePanel = Mods.AppliedEnergistics2.getItem("part", 380, 1);
		mePatternTerminal = Mods.AppliedEnergistics2.getItem("part", 340, 1);
		mePatternTerminalEx = Mods.AppliedEnergistics2.getItem("part", 360, 1);
		mePortableCell = Mods.AppliedEnergistics2.getItem("part", 480, 1);
		meFluidTerminal = Mods.AppliedEnergistics2.getItem("part", 520, 1);
		inputBus = Mods.AppliedEnergistics2.getItem("part", 240, 1);
		fluidInputBus = Mods.AppliedEnergistics2.getItem("part", 241, 1);
		outputBus = Mods.AppliedEnergistics2.getItem("part", 260, 1);
		fluidOutputBus = Mods.AppliedEnergistics2.getItem("part", 261, 1);
		craftingUnit = Mods.AppliedEnergistics2.getItem("crafting_unit");
		parallelProcessingUnit = Mods.AppliedEnergistics2.getItem("crafting_accelerator");
		craftingStorage1k = Mods.AppliedEnergistics2.getItem("crafting_storage_1k");
		craftingStorage4k = Mods.AppliedEnergistics2.getItem("crafting_storage_4k");
		craftingStorage16k = Mods.AppliedEnergistics2.getItem("crafting_storage_16k");
		craftingStorage64k = Mods.AppliedEnergistics2.getItem("crafting_storage_64k");
		energyCell = Mods.AppliedEnergistics2.getItem("energy_cell");
		denseEnergyCell = Mods.AppliedEnergistics2.getItem("dense_energy_cell");
		molecularAssembler = Mods.AppliedEnergistics2.getItem("molecular_assembler");
		logicModel = Mods.AppliedEnergistics2.getItem("material", 13, 1);
		logicBase = Mods.AppliedEnergistics2.getItem("material", 18, 1);
		logicProcessor = Mods.AppliedEnergistics2.getItem("material", 22, 1);
		calculationModel = Mods.AppliedEnergistics2.getItem("material", 14, 1);
		calculationBase = Mods.AppliedEnergistics2.getItem("material", 16, 1);
		calculationProcessor = Mods.AppliedEnergistics2.getItem("material", 23, 1);
		engineeringModel = Mods.AppliedEnergistics2.getItem("material", 15, 1);
		engineeringBase = Mods.AppliedEnergistics2.getItem("material", 17, 1);
		engineeringProcessor = Mods.AppliedEnergistics2.getItem("material", 24, 1);
		siliconModel = Mods.AppliedEnergistics2.getItem("material", 19, 1);
		skyCompass = Mods.AppliedEnergistics2.getItem("sky_compass");
		forming = Mods.AppliedEnergistics2.getItem("material", 43, 1);
		breaking = Mods.AppliedEnergistics2.getItem("material", 44, 1);
		siliconFiber = Mods.AppliedEnergistics2.getItem("part", 140, 1);
		meGlassCable = Mods.AppliedEnergistics2.getItem("part", 16, 1);
		meCable = Mods.AppliedEnergistics2.getItem("part", 36, 1);
		meCableDense = Mods.AppliedEnergistics2.getItem("part", 516, 1);
		meCableSmart = Mods.AppliedEnergistics2.getItem("part", 56, 1);
		p2p = Mods.AppliedEnergistics2.getItem("part", 460, 1);
		fluixpearl = Mods.AppliedEnergistics2.getItem("material", 9, 1);
		basicCard = Mods.AppliedEnergistics2.getItem("material", 25, 1);
		advancedCard = Mods.AppliedEnergistics2.getItem("material", 28, 1);
		blankPattern = Mods.AppliedEnergistics2.getItem("material", 52, 1);
		meStorageCell = Mods.AppliedEnergistics2.getItem("material", 39, 1);
		cell1k = Mods.AppliedEnergistics2.getItem("material", 35, 1);
		storage1k = Mods.AppliedEnergistics2.getItem("storage_cell_1k");
		cell4k = Mods.AppliedEnergistics2.getItem("material", 36, 1);
		storage4k = Mods.AppliedEnergistics2.getItem("storage_cell_4k");
		cell16k = Mods.AppliedEnergistics2.getItem("material", 37, 1);
		storage16k = Mods.AppliedEnergistics2.getItem("storage_cell_16k");
		cell64k = Mods.AppliedEnergistics2.getItem("material", 38, 1);
		storage64k = Mods.AppliedEnergistics2.getItem("storage_cell_64k");
		fluidCell1k = Mods.AppliedEnergistics2.getItem("material", 54, 1);
		fluidStorage1k = Mods.AppliedEnergistics2.getItem("fluid_storage_cell_1k");
		fluidCell4k = Mods.AppliedEnergistics2.getItem("material", 55, 1);
		fluidStorage4k = Mods.AppliedEnergistics2.getItem("fluid_storage_cell_4k");
		fluidCell16k = Mods.AppliedEnergistics2.getItem("material", 56, 1);
		fluidStorage16k = Mods.AppliedEnergistics2.getItem("fluid_storage_cell_16k");
		fluidCell64k = Mods.AppliedEnergistics2.getItem("material", 57, 1);
		fluidStorage64k = Mods.AppliedEnergistics2.getItem("fluid_storage_cell_64k");
		energyAcceptor = Mods.AppliedEnergistics2.getItem("energy_acceptor");
	}
}

